In [2]:
import pandas as pd
import ast

In [3]:
df_raw = pd.read_csv('../data/scraped/raw_data.csv')
df_raw.head(1)

,name,email,id,meta,question,answer,rates
0,Şahbaz Məmmədov,ca***@gmail.com,ID: 10826,"['23/04/2026', 'Oxunub: 62', 'Orta qiymət: 0']",Hüquqi şəxsin fəaliyyəti 10 ildir dayandırılmı...,"Bildiririk ki, hüquqi şəxsin ləğv edilməsi pro...","['0', '(0 Orta qiymət)']"

In [4]:
df_raw.shape

(5772, 7)

In [5]:
df = df_raw.copy()

In [6]:
df.isnull().sum()

name        0
email       0
id          0
meta        0
question    0
answer      1
rates       0
dtype: int64

In [7]:
df = df[~df.answer.isnull()]

In [8]:
df.id = df.id.apply(lambda x: x.strip('ID: ')).astype(int)

In [9]:
df[['name', 'question', 'answer', 'email']] = df[['name', 'question', 'answer', 'email']].map(lambda x: x.strip())

In [10]:
import ast 
df[['answer_date', 
    'read_count', 
    'average_rate']] = df['meta'].apply(ast.literal_eval).apply(lambda x: (x[0], 
                                                                           x[1], 
                                                                           x[2])).apply(pd.Series)

df[['answer_date', 'read_count', 'average_rate']]

     answer_date   read_count    average_rate
0     23/04/2026   Oxunub: 62  Orta qiymət: 0
1     22/04/2026   Oxunub: 62  Orta qiymət: 0
2     21/04/2026   Oxunub: 88  Orta qiymət: 4
3     20/04/2026  Oxunub: 118  Orta qiymət: 5
4     16/04/2026  Oxunub: 131  Orta qiymət: 0
...          ...          ...             ...
5767  28/12/2018   Oxunub: 86  Orta qiymət: 4
5768  28/12/2018  Oxunub: 132  Orta qiymət: 4
5769  18/05/2018   Oxunub: 44  Orta qiymət: 5
5770  29/04/2017  Oxunub: 129  Orta qiymət: 5
5771  13/12/2015  Oxunub: 169  Orta qiymət: 4

[5771 rows x 3 columns]

In [11]:
df[['answer_date', 
    'read_count', 
    'average_rate']] = df['meta'].apply(ast.literal_eval).apply(lambda x: (pd.to_datetime(x[0], dayfirst = True), 
                                                                           int(x[1].strip('Oxunub: ')), 
                                                                           int(x[2].strip('Orta qiymət: ')))
                                                                ).apply(pd.Series)

df[['answer_date', 'read_count', 'average_rate']]

     answer_date  read_count  average_rate
0     2026-04-23          62             0
1     2026-04-22          62             0
2     2026-04-21          88             4
3     2026-04-20         118             5
4     2026-04-16         131             0
...          ...         ...           ...
5767  2018-12-28          86             4
5768  2018-12-28         132             4
5769  2018-05-18          44             5
5770  2017-04-29         129             5
5771  2015-12-13         169             4

[5771 rows x 3 columns]

In [12]:
df['rate_count'] = df['rates'].apply(ast.literal_eval).apply(lambda x: x[1]).str.extract(r'(\d+)').astype(int)

In [13]:
df.drop(['rates', 'meta',  'email'], axis = 1, inplace = True)

In [14]:
df.head()

,name,id,question,answer,answer_date,read_count,average_rate,rate_count
0,Şahbaz Məmmədov,10826,Hüquqi şəxsin fəaliyyəti 10 ildir dayandırılmı...,"Bildiririk ki, hüquqi şəxsin ləğv edilməsi pro...",2026-04-23,62,0,0
1,Lalə Namazova,10820,Salam. Mən VÖEN-in ləğvi ilə bağlı müraciət et...,“Vergi uçotuna alınmış vergi ödəyiciləri barəd...,2026-04-22,62,0,0
2,Orxan Quliyev,10817,Qeyri-neft sektorunda yekun hesablanmış məbləğ...,"Bildiririk ki, fiziki şəxsin iş yerindən əldə ...",2026-04-21,88,4,3
3,Tural Mamedov,10815,Ailədə iki azyaşlı uşaq vardır. Valideynlərdən...,Vergi Məcəlləsinin 102.5-ci maddəsinə əsasən q...,2026-04-20,118,5,3
4,Raqif Zalov Meherrem,10809,Salam. Qeyd etdiyim çek niyə ləğv olunub? Fisc...,Sorğunuzda qeyd olunan məsələnin araşdırılması...,2026-04-16,131,0,0

In [15]:
df.question[1805]

'Təmsil etdiyim Hüquqi şəxsin kommersiya mübahisəsi ilə əlaqədar məcburi mediasiya üçün mediasiya şurasına müracət edikdən sonra, mediasiya xidmətlərinin göstərilməsi üçün tələb edilən rüsumu ödəmək zərurəti yarandı. Mediasiya şurasına rüsumu ödəmək üçün tərəflər arasında müqavilə imzalanmalı olduğunu (təmsil etdiyim hüquqi şəxs və Mediator arasında) və bunun əsasında nağdsız ödəniş edilməsi mümkünlüyü bildirildi. Həmçinin mediasiya şurasına mediasiya haqqında qanunun maddələri" mediasiya xidmətlərinin göstərilməsinə dair müqavilə – mediator və ya mediasiya təşkilatı ilə tərəflər arasında mediasiya xidmətlərinin göstərilməsi üçün imzalanan yazılı müqavilə;" :mediasiya prosesinin tətbiqi barədə müqavilə – mübahisənin (mövcud və ya gələcəkdə yarana biləcək) mediasiya prosesi vasitəsilə həlli üçün tərəflər arasında bağlanan yazılı razılaşma;Mediasiya tərəflərin qarşılıqlı razılığı ilə bağlanan “mediasiya prosesinin tətbiqi barədə müqavilə” əsasında (bu Qanunun 21.1-ci maddəsi nəzərə alınmaqla) həyata keçirilir.Mediasiya prosesi tərəflər arasında bağlanan “mediasiya prosesinin tətbiqi barədə müqavilə” əsasında və ya bu Qanunun 28-ci və 29-cu maddələrinə uyğun olaraq ilkin mediasiya sessiyasında iştirak etməklə həyata keçirilir.\r\n21.2. “Mediasiya prosesinin tətbiqi barədə müqavilə” tərəflər arasında yaranmış mübahisənin məhkəməyə verilməsinə qədər və ya məhkəmədə işə baxılan zaman tətbiq edilə bilər. əlavə olaraq digər normativ aktlar Azərbaycan Respublikasında nağdsız hesablaşmalar və pul köçürmələri haqqında təlimat"ın təsdiq edilməsi barədə\r\nAZƏRBAYCAN RESPUBLİKASI MƏRKƏZİ BANKIN İDARƏ HEYƏTİNİN QƏRARI 19/1 \r\nBakı şəhəri 17 sentyabr 2013-cü il\r\nMülki dövriyyənin subyektləri tərəfindən nağdsız hesablaşmaların forması tərəflər arasında bağlanmış müqavilə ilə müəyyənləşdirilir.\r\nVergilər məcəlləsi\r\n50.1.11. nağdsız hesablaşmaların həyata keçirilməsi ilə bağlı qanunla müəyyən olunmuş tələblərə əməl olunmasına nəzarət edilməsi;  mediatorun diqqətinə çatdırılsa da müqavilə bağlanmadan birbaşa təqdim edilmiş rekvizitlər üzrə rüsumun ödənilməsi zəruriliyi bildirilmişdir  həmçinin aşağıdakı məzmunda cavab ümvanlanmışdır.\r\n"Mediasiya xidmətlərinin göstəriləməsinə görə müvafiq müqavilənin bağlanmaması və mediasiya prosesinə dair xərclərin ödənilməsi qaydası barədə məlumatın verilməsi ilə bağlı müradiətinizə Mediasiya Şurasında baxılmışdır.\r\nBildiririk ki, “Mediasiya haqqında” Azərbaycan Respublikasının Qanununa (bunda sonra – Qanun) əsasən mediasiya – mediatorun (mediatorların) vasitəçiliyi ilə tərəflər arasında yaranmış mübahisənin qarşılıqlı razılıq əsasında həlli ilə bağlı Qanunla müəyyən olunan prosesdir. \r\nQanunun 21.1-ci maddəsinə əsasən mediasiya prosesi tərəflərin qarşılıqlı razılığı ilə bağlanan “mediasiya prosesinin tətbiqi barədə müqavilə” əsasında və ya Qanunun 28-ci və 29-cu maddələrinə uyğun olaraq ilkin mediasiya sessiyasında iştirak etməklə həyata keçirilir.\r\nQeyd edilməlidir ki, Qanunun tələbinə uyğun olaraq, kommersiya mübahisələri, həmçinin ailə və əmək münasibətlərindən irəli gələn mübahisələr üzrə məhkəməyə müraciət etməmişdən əvvəl ilkin mediasiya sessiyasında iştirak tələb olunur.\r\nMediator ilkin mediasiya sessiyasında iştirak etmək üçün müraciət edən tərəflərə mediasiya prosesinin mahiyyətini, üstünlüklərini və qaydalarını izah edir, tərəflərlə birgə və ayrılıqda görüşlər keçirir. Həmin gün və ya tərəflərin müraciəti ilə mediatorun təyin etdiyi başqa gün tərəflər sonrakı mediasiya sessiyalarında iştirak etmək istəyib-istəmədiklərinə dair qərar verməlidirlər. \r\nQanunun 29-cü maddəsinə əsasən tərəflər və ya onlardan biri ilkin mediasiya sessiyasında iştirak etmədikdə və ya iştirak etməkdən yazılı şəkildə imtina etdikdə, mediator sessiyada iştirak edən və etməyən tərəfləri qeyd etməklə “İlkin mediasiya sessiyasında iştirak edilməməsi” ilə bağlı arayışı həmin şəxslərə təqdim edir.\r\nTərəflər ilkin mediasiya sessiyasında iştirak etdikdə lakin tərəflərdən biri və ya hər ikisi mediasiya prosesini davam etdirməyə razılıq vermədikdə, mediator mediasiya prosesinə xitam verir və “İlkin mediasiya sessiyasından sonra prosesin davam etdirilə bilməməsi” ilə bağlı arayışı tərəflərə təqdim edir.\r\nTərəflər mediasiya prosesini davam etdirməyə qərar verdikdə isə tərəflər arasında “mediasiya prosesinin tətbiqi barədə müqavilə” bağlanılır və mediasiya prosesi həyata keçirilir.\r\nMüraciətinizdə də qeyd etdiyiniz kimi, Qanunun 36-cı maddəsinə əsasən ilkin mediasiya sessiyası zamanı mediasiya xidmətinin göstərilməsinə görə haqqın və digər xərclərin məbləği Azərbaycan Respublikası Nazirlər Kabinetinin 2019-cu il 15 iyul tarixli 308 nömrəli Qərarı ilə təsdiq edilmişdir. Sonraki mediasiya sessiyası ilə bağlı xərclər isə tərəflərlə mediator və ya mediasiya təşkilatı arasında “mediasiya xidmətlərinin göstərilməsinə dair müqavilə” ilə müəyyən olunur.\r\nQanunun 36.4-cü maddəsinə əsasən kommersiya mübahisələri, həmçinin ailə və əmək münasibətlərindən irəli gələn mübahisələr üzrə ilkin mediasiya sessiyasında iştirak edilidiyi hallarda “mediasiya xidmətlərinin göstərilməsinə dair müqavilə” tərəflər mediasiya prosesini davam etdirməyə qərar verdikdə, sonrakı mediasiya sessiyası başlanana qədər imzalanmalıdır.\r\nGöründüyü kimi, Qanununda “mediasiya xidmətlərinin göstərilməsinə dair müqavilə”nin yalnız “mediasiya prosesinin tətbiqi barədə müqavilə” əsasında mediasiya xidmətlərinin göstərilməsinə görə bağlanılması nəzərdə tutulmuşdur. \r\nMediasiya xərclərinin ödənilməsi qaydasına gəldikdə isə bildiririk ki, “Nağdsız hesablaşmalar haqqında” Azərbaycan Respublikasının Qanununa əsasən bir şəxsin bank hesabından digər şəxsin bank hesabına köçürülməklə (o cümlədən ödəniş alətləri (ödəniş kartları, ödəniş tapşırığı və s.) və ödəniş vasitələri (mobil telefon aparatları, kompüter və digər avadanlıq) ilə həyata keçirilən hesablaşmalar, ödəniş terminalları ilə həyata keçirilən hesablaşmalar və birbaşa nağd qaydada satıcının bank hesabına köçürülməklə həyata keçirilən hesablaşmalar nağdsız hesablaşma hesab olunur.\r\nBununla belə qeyd edilməlidir ki, mediasiya xərcləri ilə bağlı ödənişlər adıçəkilən Qanunun 3.4-cü maddəsində yalnız nağdsız qaydada həyata keçirilən ödənişlər sırasında göstərilməmişdir.\r\nXahiş edirik nəzərə alasınız."\r\nHazırkı vəziyyətdə qeyd edilən məsələyə münasibət bildirmənizi xahiş edirəm.'

In [16]:
df.head(1)

,name,id,question,answer,answer_date,read_count,average_rate,rate_count
0,Şahbaz Məmmədov,10826,Hüquqi şəxsin fəaliyyəti 10 ildir dayandırılmı...,"Bildiririk ki, hüquqi şəxsin ləğv edilməsi pro...",2026-04-23,62,0,0

In [21]:
df.to_csv('..\data\processed\clean_data.csv', index = False)